### ISSUE TITLE
Crash on Android 7

### ISSUE THREAD

**Issue by arkilis** [chintan369/MultiImagePicker#2]
`java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/FragmentActivity;
        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:86)
        at com.bumptech.glide.Glide.with(Glide.java:657)
        at com.creativechintak.multiimagepicker.adapter.ImagesAdapter.onBindViewHolder(ImagesAdapter.kt:36)
        at com.creativechintak.multiimagepicker.adapter.ImagesAdapter.onBindViewHolder(ImagesAdapter.kt:14)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
        at android.view.View.measure(View.java:19967)
        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:733)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
        at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
        at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6132)
        at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
2022-07-30 07:32:58.952 4473-4473/? E/AndroidRuntime:     at com.android.internal.policy.DecorView.onMeasure(DecorView.java:856)
        at android.view.View.measure(View.java:19967)
        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2642)
        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1717)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1981)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1593)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7089)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:883)
        at android.view.Choreographer.doCallbacks(Choreographer.java:689)
        at android.view.Choreographer.doFrame(Choreographer.java:624)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:869)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:6385)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1096)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.FragmentActivity" on path: DexPathList[[zip file "/data/app/com.flyingbits-1/base.apk"],nativeLibraryDirectories=[/data/app/com.flyingbits.-1/lib/arm64, /system/lib64, /vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`

**Comment by bnnguyen8** [comment]
I updated by moving all classes related to PermissionUtils into MultiImagePicker library folder, because com.github.Promact:dynamic-permission-handling-android:1.0.1 is not available anymore. Then it has worked fine for me, I hope my info helps someone later.

**Comment by bnnguyen8** [comment]
And use implementation 'com.github.bumptech.glide:glide:4.15.1' with 4.15.1 instead of 3.8.0
